### ISSUE TITLE
线程数量

### ISSUE THREAD

**Issue by jackfrow** [cntrump/SFDispatchQueuePool#2]
线程池是用来控制并发任务和线程数量的,你这样做还是会开无数的线程出来。

**Comment by cntrump** [comment]
你说的对，这个不能算线程池，和 NSOperationQueue 一样。

但是不会创建无数等待线程，后面插入的任务都在 serial 队列中管理，只有一个等待线程。

**Comment by jackfrow** [comment]
ok.
